# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csvreader.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(808, 600)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 791, 361))
        self.tableView.setObjectName("tableView")
        self.StrictDomButton = QtWidgets.QPushButton(Dialog)
        self.StrictDomButton.setGeometry(QtCore.QRect(10, 380, 121, 28))
        self.StrictDomButton.setObjectName("StrictDomButton")
        self.FaibleDomButton = QtWidgets.QPushButton(Dialog)
        self.FaibleDomButton.setGeometry(QtCore.QRect(140, 380, 121, 28))
        self.FaibleDomButton.setObjectName("FaibleDomButton")
        self.ElimStrictDomButton = QtWidgets.QPushButton(Dialog)
        self.ElimStrictDomButton.setGeometry(QtCore.QRect(270, 380, 131, 28))
        self.ElimStrictDomButton.setObjectName("ElimStrictDomButton")
        self.ElimFaibleDomButton = QtWidgets.QPushButton(Dialog)
        self.ElimFaibleDomButton.setGeometry(QtCore.QRect(410, 380, 131, 28))
        self.ElimFaibleDomButton.setObjectName("ElimFaibleDomButton")
        self.NashButton = QtWidgets.QPushButton(Dialog)
        self.NashButton.setGeometry(QtCore.QRect(550, 380, 121, 28))
        self.NashButton.setObjectName("NashButton")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 420, 791, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.ParetoButton = QtWidgets.QPushButton(Dialog)
        self.ParetoButton.setGeometry(QtCore.QRect(680, 380, 121, 28))
        self.ParetoButton.setObjectName("ParetoButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CSV Analysis"))
        self.StrictDomButton.setText(_translate("Dialog", "Strictement Dom"))
        self.FaibleDomButton.setText(_translate("Dialog", "Faiblement Dom"))
        self.ElimStrictDomButton.setText(_translate("Dialog", "Elimin Succ Strict"))
        self.ElimFaibleDomButton.setText(_translate("Dialog", "Elimin Succ Faible"))
        self.NashButton.setText(_translate("Dialog", "Nash"))
        self.ParetoButton.setText(_translate("Dialog", "Equilb Pareto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
