# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_playerInputForm(object):
    def setupUi(self, playerInputForm):
        playerInputForm.setObjectName("playerInputForm")
        playerInputForm.resize(444, 246)
        self.gridLayoutWidget = QtWidgets.QWidget(playerInputForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_label.setObjectName("label_label")
        self.gridLayout.addWidget(self.label_label, 0, 1, 1, 1)
        self.generateButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.generateButton.setObjectName("generateButton")
        self.gridLayout.addWidget(self.generateButton, 5, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.addPlayerButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.addPlayerButton.setObjectName("addPlayerButton")
        self.gridLayout.addWidget(self.addPlayerButton, 4, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.playerStrats_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.playerStrats_1.setPlaceholderText("")
        self.playerStrats_1.setObjectName("playerStrats_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.playerStrats_1)
        self.playerStrats_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.playerStrats_2.setObjectName("playerStrats_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.playerStrats_2)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 2)

        self.retranslateUi(playerInputForm)
        QtCore.QMetaObject.connectSlotsByName(playerInputForm)

    def retranslateUi(self, playerInputForm):
        _translate = QtCore.QCoreApplication.translate
        playerInputForm.setWindowTitle(_translate("playerInputForm", "Dialog"))
        self.label_label.setText(_translate("playerInputForm", "Strategies"))
        self.generateButton.setText(_translate("playerInputForm", "Generate CSV"))
        self.addPlayerButton.setText(_translate("playerInputForm", "Add +"))
        self.label_2.setText(_translate("playerInputForm", "Player 2"))
        self.label_1.setText(_translate("playerInputForm", "Player 1"))
        self.playerStrats_1.setText(_translate("playerInputForm", "2"))
        self.playerStrats_2.setText(_translate("playerInputForm", "2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    playerInputForm = QtWidgets.QDialog()
    ui = Ui_playerInputForm()
    ui.setupUi(playerInputForm)
    playerInputForm.show()
    sys.exit(app.exec_())
