# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(167, 183)
        self.generateButton = QtWidgets.QPushButton(Dialog)
        self.generateButton.setGeometry(QtCore.QRect(11, 150, 151, 28))
        self.generateButton.setObjectName("generateButton")
        self.addPlayerButton = QtWidgets.QPushButton(Dialog)
        self.addPlayerButton.setGeometry(QtCore.QRect(11, 120, 151, 28))
        self.addPlayerButton.setObjectName("addPlayerButton")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(11, 100, 151, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_label_2 = QtWidgets.QLabel(Dialog)
        self.label_label_2.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_label_2.setObjectName("label_label_2")
        self.label_label = QtWidgets.QLabel(Dialog)
        self.label_label.setGeometry(QtCore.QRect(70, 10, 216, 16))
        self.label_label.setObjectName("label_label")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 151, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.playerStrats_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.playerStrats_1.setPlaceholderText("")
        self.playerStrats_1.setObjectName("playerStrats_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.playerStrats_1)
        self.playerStrats_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.playerStrats_2.setObjectName("playerStrats_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.playerStrats_2)
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.generateButton.setText(_translate("Dialog", "Generate CSV"))
        self.addPlayerButton.setText(_translate("Dialog", "Add +"))
        self.label_label_2.setText(_translate("Dialog", "Players"))
        self.label_label.setText(_translate("Dialog", "Strategies"))
        self.label_2.setText(_translate("Dialog", "Player 2"))
        self.playerStrats_1.setText(_translate("Dialog", "2"))
        self.playerStrats_2.setText(_translate("Dialog", "2"))
        self.label_1.setText(_translate("Dialog", "Player 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
