# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(404, 164)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 2, 388, 106))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 404, 26))
        self.menubar.setObjectName("menubar")
        self.menuNew_Game = QtWidgets.QMenu(self.menubar)
        self.menuNew_Game.setObjectName("menuNew_Game")
        self.menuOpen_CSV = QtWidgets.QMenu(self.menubar)
        self.menuOpen_CSV.setObjectName("menuOpen_CSV")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNGPure = QtWidgets.QAction(MainWindow)
        self.actionNGPure.setObjectName("actionNGPure")
        self.actionNGMixed = QtWidgets.QAction(MainWindow)
        self.actionNGMixed.setEnabled(False)
        self.actionNGMixed.setObjectName("actionNGMixed")
        self.actionRPure = QtWidgets.QAction(MainWindow)
        self.actionRPure.setObjectName("actionRPure")
        self.actionRMixed = QtWidgets.QAction(MainWindow)
        self.actionRMixed.setEnabled(False)
        self.actionRMixed.setObjectName("actionRMixed")
        self.menuNew_Game.addAction(self.actionNGPure)
        self.menuNew_Game.addAction(self.actionNGMixed)
        self.menuOpen_CSV.addAction(self.actionRPure)
        self.menuOpen_CSV.addAction(self.actionRMixed)
        self.menubar.addAction(self.menuNew_Game.menuAction())
        self.menubar.addAction(self.menuOpen_CSV.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Game Theory - Project"))
        self.label.setText(_translate("MainWindow", "StratSolver™"))
        self.label_2.setText(_translate("MainWindow", "by MOUSSAOUI Ahmed ©2020"))
        self.menuNew_Game.setTitle(_translate("MainWindow", "New Game"))
        self.menuOpen_CSV.setTitle(_translate("MainWindow", "Open CSV"))
        self.actionNGPure.setText(_translate("MainWindow", "Pure"))
        self.actionNGMixed.setText(_translate("MainWindow", "Mixed"))
        self.actionRPure.setText(_translate("MainWindow", "Pure"))
        self.actionRMixed.setText(_translate("MainWindow", "Mixed"))